# Site
repository: pullannagari/pullannagari.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Sudhir Pullannagari
title: Lead Software Engineer
email: sudhir.123reddy@hotmail.com
website: https://pullannagari.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: pullannagari
linkedin_username: sudhirreddyp

# # Additional icon links
# additional_links:
#   - title: itsgoingto.be
#     icon: fas fa-globe
#     url: https://www.itsgoingto.be

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Experienced, motivated, and <mark>highly skilled backend developer</mark> with over a decade of expertise in designing and developing <mark>distributed systems</mark> and <mark>stream processing applications</mark>. Naturally inclined to tackle and solve complex problems, adept at leading the design and development of mission-critical applications, optimizing performance, and implementing best practices. Proficient in <mark>building scalable, resilient, and high-performance systems that handle large volumes of data in real-time</mark>. Throughout my career, I have successfully led multiple projects from conception to deployment, ensuring robust architecture and seamless integration with existing systems. My experience includes designing <mark>microservices architectures, implementing event-driven systems, and utilizing technologies such as Kafka, Kinesis, Spark, and Flink for real-time data processing</mark>. I have a strong background in <mark>AWS</mark> cloud platforms, leveraging their services to build and deploy scalable applications. I am skilled in various programming languages, including <mark>Java, Python</mark> and have extensive experience with <mark>containerization and orchestration</mark> tools like Docker and Kubernetes. My expertise also extends to database management, both <mark>SQL and NoSQL</mark>, ensuring optimal data storage and retrieval. In addition to technical skills, I am committed to fostering a collaborative team environment, mentoring junior developers, and promoting best practices in software development. My goal is to continuously innovate and deliver high-quality solutions that drive business success.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Lead Software Engineer - Merchandising Platform, NIKE, INC
        link: nike.com
        sub_title: Lead Software Engineer
        caption: April 2017 - Present
        description: | # this will include new lines to allow paragraphs
          ▪ Designed and developed marketplace aggregation for Geo, Country aggregations enabling efficient line planning and resulted in annual savings of ~18M for additional geo/country maintenance and operations.
          ▪ Designed and developed a generic template(cookie-cutter) pattern for developing common backend for platform applications to increase the speed of delivery and promote consistency, extensibility to add/choose more capabilities.
          ▪ Steered design and architecture decisions by engaging in PoC projects and strategic sessions, enhancing innovation and process efficiency.
          ▪ Developed application(s) backend CRUD and Search for merch platform to support activities like planning of architecture of products, prioritization of those products for global and marketplaces, build/manage Assortments for all Channels, Retailers & consumer segments.
          ▪ Designed, implemented highly scalable RESTful and GraphQL merch platform services to handle ~30M requests per day.
          ▪ Integrated near real-time events and streaming from domain applications, transformed, aggregated for product data consumption using Python, Elasticsearch, Kinesis, and generic Kafka implementation(Nike Streaming Platform).
          ▪ Employed Docker for containerization, enabling application debugging, volume sharing, and custom networking and skilled in deploying and managing applications on Kubernetes clusters using kubectl and Helm for streamlined orchestration.
          ▪ Implemented robust security the application divesting basic auth, designed and Implemented OAuth 2.0 with OpenID connect (OKTA), confidentiality for multiple applications, data and product images through Authorization Code and Client Credentials flows.
          ▪ Designed and implemented automated pricing microservices for country products adhering to local governing rules, carryover logic, global, geo attribution improving accuracy and saving about 30% of merchandisers, product line manger’s man hours.
          ▪ Mentored junior engineers, and performed code reviews for maintainability, extensibility, best practices, consistency.
          ▪ Automated regression testing, BDD using cucumber, fitnesse, behave, and TDD(unit testing) using, Junit, Mockito, pytest.

      - layout: left
        title: Applications Developer, Horizon BCBS NJ (Contract)
        caption: July 2016 – April 2017
        description: | # this will include new lines to allow paragraphs
          ▪ Designed & Developed backend for Member Dashboard for nurses to access member demographic, alerts, surveys, care plans, care gaps, claims, lab and medication information using NodeJS to enhance the customer experience and improve retention.
          ▪ Applied strong computer science fundamentals in data structures, algorithms, and programming languages to optimize project performance and data management.
          ▪ Implemented serverless architectures using AWS Lambda, optimizing function performance through efficient memory allocation and concurrent executions. This streamlined development, reduced infrastructure costs, and improved scalability.
          ▪ Used Spring MVC, Spring Boot, Spring Batch, Spring RESTful modules for developing the backend applications and integrations.
          ▪ Adhered to 12-Factor methodology for building and maintaining software-as-a-service apps.
          ▪ Lead migration of SVN to GITHUB, NEXUS to Artifactory for storing application code and artifacts.
          ▪ Designed database schemas for the application and introduced sharding, single table design (GSI) in dynamodb for performance.
          ▪ Implemented UUID(4, 5) generation for transactional record identification to enable optimal data modeling and design.
          ▪ Used Hibernate ORM features for developing DAO tier of the app for effective use of relational databases, second-level caching (MemcacheD).
          ▪ Accustomed in applying DevOps methodologies, unifying software development and operations.

      - layout: left
        title: Technology Analyst, Telstra Corporation/Global (Contract)
        caption: August 2012 - April 2016
        description: | # this will include new lines to allow paragraphs
          ▪ Implemented multithreading to bill multiple accounts concurrently and generate invoices, validate the CDR usage flown in from the upstream mediation systems.
          ▪ Used Spring-JDBC to access the data from database server by implementing JDBCTemplate provided by spring framework.
          ▪ Used Spring JMS and ActiveMQ for data exchange between various subsystems.
          ▪ Developed XSD’s and WSDL files based on the Service Endpoint Interface and consumed SOAP services by generating stubs, marshaling/unmarshalling model objects using JAXB.
          ▪ Developed and tested stored procedures to implement business logic using TOAD.
          ▪ Developed user-friendly web-based GUI using HTML5, and CSS3, Used JavaScript, AJAX for client-side validations and efficient interactions.
          ▪ Implemented Spring MVC architecture, worked on developing the controller, Spring & Hibernate integration in Persistence Layer.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: text
        title: Jawaharlal Nehru Technological University
        caption: Bachelor of Technology, Computer Science and Engineering
        description: During my degree at JNTU, I developed a strong foundation in computer science and engineering, including advanced data structures, algorithms, problem solving and programming languages. I also gained experience in software development, database management, and system design.

  - title: Certifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: text
        title: AWS Certified Developer (2018 edition)
        description: | # this will include new lines to allow paragraphs
          AWS Certified Developer - Associate validates technical expertise in developing and maintaining applications on the AWS platform. This certification is intended for individuals who perform a development role and have one or more years of hands-on experience developing and maintaining an AWS-based application.
      - layout: text
        title: Certified SAFe® 4 Practitioner
        description: | # this will include new lines to allow paragraphs
          The SAFe® Practitioner certification program is for software developers, testers, product managers, and product owners. The certification covers the principles of the Agile framework, Lean thinking, and product development flow.
      - layout: text
        title: Microsoft certified HTML 5/CSS 3, JS Associate
        description: | # this will include new lines to allow paragraphs
          The Microsoft Certified HTML5, CSS3, and JavaScript certification is for developers who have a minimum of one to two years of experience developing HTML, CSS, and JavaScript applications.
      - layout: text
        title: Domain Driven Design, API Standards 101, 201
        description: | # this will include new lines to allow paragraphs
          Domain-Driven Design (DDD) is an approach to software development that aligns the domain model with the business domain. API Standards 101, 201 are courses that cover the basics of API design and development, including RESTful and GraphQL APIs.

  - title: Skills # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      Python3, Java 8, JSON, YAML, Spring, Hibernate, Redis, Kafka, SQL/NoSQL, PLSQL, Oracle, Mongo DB, Kubernetes, Docker, UNIX, Shell Script, github, RESTful, GraphQl, SOAP, Jenkins, kubernetes, NewRelic, Splunk, TDD/BDD, Opensearch, AWS Services (Lambda, Kinesis, ECS, EC2, S3, RDS, API GW, SNS/SQS, elasticsearch, DynamoDB, Cloudwatch, etc.), Terraform, OAuth 2.0

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
